name: hungrx_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3+19

environment:
  sdk: ^3.5.3

dependencies:
  animated_flip_counter: ^0.3.4
  animated_weight_picker: ^1.0.3
  bloc: ^9.0.0
  cartesian_vision: ^0.0.2
  confetti: ^0.8.0
  connectivity_plus: ^6.1.3
  country_code_picker: ^3.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_heatmap_calendar: ^1.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_material_symbols: ^0.0.4
  flutter_timezone: ^4.1.0
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.2
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_network: ^2.5.6
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  lucide_icons: ^0.257.0
  material_symbols_icons: ^4.2801.0
  otp_autofill: ^4.1.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.3
  pinput: ^5.0.0
  purchases_flutter: ^8.4.5
  rxdart: ^0.28.0
  share_plus: ^10.1.2
  shared_preferences: ^2.4.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.4
  sms_autofill: ^2.4.1
  star_rating: ^0.11.0
  syncfusion_flutter_charts: ^28.1.41
  timezone: ^0.10.0
  upgrader: ^11.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/new_hungrx.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: digifont
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF

flutter_native_splash:
  color: "#BADA55"
  image: assets/images/companylogo.jpeg
  android_12:
    image: assets/images/companylogo.jpeg
    color: "#BADA55"
