name: hungrx_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_flip_counter: ^0.3.4
  animated_weight_picker: ^1.0.3
  bloc: ^8.1.4
  cartesian_vision: ^0.0.2
  confetti: ^0.8.0
  connectivity_plus: ^6.1.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_heatmap_calendar: ^1.0.5
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.2
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_network: ^2.5.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lucide_icons: ^0.257.0
  percent_indicator: ^4.2.3
  pinput: ^5.0.0
  rxdart: ^0.28.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  star_rating: ^0.11.0
  syncfusion_flutter_charts: ^27.1.50
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: digifont
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
